use crate::core::header::BlockHeader;
use crate::crypto::hash::Hash;
use crate::ledger::transaction::{Transaction, Output};
use std::time::{SystemTime, UNIX_EPOCH};

pub struct Genesis;

impl Genesis {
    /// Menciptakan Genesis Block pertama secara permanen
        pub fn build(
                founder_pub_key: [u8; 32],
                        community_pool_pub_key: [u8; 32],
                                dev_fund_pub_key: [u8; 32],
                                    ) -> (BlockHeader, Transaction) {
                                            
                                                    // Total Supply: 1.000.000.000 MEMEOS
                                                            // Satuan terkecil (misal 1 MEMEOS = 10^8 units)
                                                                    let total_supply: u64 = 1_000_000_000_000_000; 
                                                                            
                                                                                    let founder_amount = (total_supply * 40) / 100;    // 40%
                                                                                            let community_amount = (total_supply * 50) / 100;  // 50%
                                                                                                    let dev_fund_amount = total_supply - founder_amount - community_amount; // Sisanya (10%)

                                                                                                            // Membuat Transaksi Genesis (Coinbase tanpa Input)
                                                                                                                    let genesis_tx = Transaction {
                                                                                                                                inputs: vec![], // Genesis tidak butuh input karena ini penciptaan awal
                                                                                                                                            outputs: vec![
                                                                                                                                                            Output {
                                                                                                                                                                                value: founder_amount,
                                                                                                                                                                                                    recipient: founder_pub_key,
                                                                                                                                                                                                                        data: Some(b"MEMEOS Founder Allocation".to_vec()),
                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                        Output {
                                                                                                                                                                                                                                                                            value: community_amount,
                                                                                                                                                                                                                                                                                                recipient: community_pool_pub_key,
                                                                                                                                                                                                                                                                                                                    data: Some(b"MEMEOS Community Rewards Pool".to_vec()),
                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                    Output {
                                                                                                                                                                                                                                                                                                                                                                        value: dev_fund_amount,
                                                                                                                                                                                                                                                                                                                                                                                            recipient: dev_fund_pub_key,
                                                                                                                                                                                                                                                                                                                                                                                                                data: Some(b"MEMEOS Development Fund".to_vec()),
                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                        timestamp: 1704067200, // Hardcoded timestamp (misal: 1 Jan 2024 00:00:00 UTC)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let tx_root = genesis_tx.id();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Block Header Genesis
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let header = BlockHeader {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            version: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        previous_hash: Hash::from([0u8; 32]), // Blok 0 tidak punya parent
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    state_root: Hash::from([0u8; 32]),    // Akan diisi Verkle Root pertama nantinya
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                tx_root,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            timestamp: 1704067200,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        nonce: 2024, // Magic number untuk identitas awal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        (header, genesis_tx)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            