use std::net::{TcpListener, TcpStream};
use std::io::{Read, Write};
use std::sync::{Arc, Mutex};
use std::thread;
use crate::network::protocol::Message;

pub struct MemeosNode {
    pub address: String,
        pub peers: Arc<Mutex<Vec<String>>>, // Daftar IP peer yang aktif
        }

        impl MemeosNode {
            pub fn new(port: u16) -> Self {
                    Self {
                                address: format!("0.0.0.0:{}", port),
                                            peers: Arc::new(Mutex::new(Vec::new())),
                                                    }
                                                        }

                                                            /// Menjalankan server node di latar belakang (Smartphone Node)
                                                                pub fn start(&self) {
                                                                        let listener = TcpListener::bind(&self.address).expect("Failed to bind port");
                                                                                println!("🌐 MEMEOS Node listening on {}", self.address);

                                                                                        for stream in listener.incoming() {
                                                                                                    match stream {
                                                                                                                    Ok(s) => {
                                                                                                                                        thread::spawn(move || {
                                                                                                                                                                Self::handle_peer(s);
                                                                                                                                                                                    });
                                                                                                                                                                                                    }
                                                                                                                                                                                                                    Err(e) => eprintln!("Connection error: {}", e),
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                /// Menangani pertukaran data biner antar peer
                                                                                                                                                                                                                                                    fn handle_peer(mut stream: TcpStream) {
                                                                                                                                                                                                                                                            let mut buffer = [0; 4096]; // Buffer biner asli
                                                                                                                                                                                                                                                                    match stream.read(&mut buffer) {
                                                                                                                                                                                                                                                                                Ok(size) if size > 0 => {
                                                                                                                                                                                                                                                                                                let msg: Result<Message, _> = bincode::deserialize(&buffer[..size]);
                                                                                                                                                                                                                                                                                                                if let Ok(message) = msg {
                                                                                                                                                                                                                                                                                                                                    match message {
                                                                                                                                                                                                                                                                                                                                                            Message::Handshake { version, .. } => {
                                                                                                                                                                                                                                                                                                                                                                                        println!("🤝 Handshake received. Protocol version: {}", version);
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                        Message::NewTransaction(tx) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    println!("💸 New transaction received: {}", tx.id().to_hex());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Message::NewBlock(block) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                println!("🧱 New block received: {}", block.hash().to_hex());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                _ => {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _ => {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /// Mengirim data ke peer lain (Broadcast)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pub fn connect_and_send(&self, peer_addr: &str, msg: Message) -> Result<(), String> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let mut stream = TcpStream::connect(peer_addr).map_err(|e| e.to_string())?;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let bytes = bincode::serialize(&msg).map_err(|e| e.to_string())?;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        stream.write_all(&bytes).map_err(|e| e.to_string())?;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Ok(())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    